### ISSUE TITLE
Add support for Pebble comments

### ISSUE THREAD

**Issue by t-ket** [ktvng/pebble#11]
# Overview
Currently there is no native support for writing comments in Pebble. We need to add functionality `#` denoted comments. Specifically: 
* Any line which begins with the `#` symbol should be considered an entire comment and ignored during parsing
* All content after a `#` symbol should be considered a comment and ignored during parsing

## Example
```python
# this is a comment
     # this is also a comment

print "hello world" # everything after this symbol is a comment
```

## Outline
The following methods will be useful to look at and start
* `GetEffectiveLine` in `./src/program.cpp`
* `LexLine` in `../src/parser/token.cpp`

**Comment by jillianzaffiro** [comment]
Users can now leave comments in their programs using '#'. However, I still can't build the test program, so @ktvng can you attempt to build the tests and let me know if it works? Once I'm able to run that, I'm sure I'll find bugs to fix in what I pushed.

**Comment by jillianzaffiro** [comment]
#34
